### ISSUE TITLE
Bad download link

### ISSUE THREAD

**Issue by pauldangerkile** [polarity/polarity-music#1]
Polarity,

The following file, which is a link on your Bitwig webpage, has the wrong file extension. It is called: "http://polaritymusic.s3.amazonaws.com/Polarity-CluelessLiquid-Bitwig-Project.zip.mp3". It should actually be called: "http://polaritymusic.s3.amazonaws.com/Polarity-CluelessLiquid-Bitwig-Project.zip".

Thank you,
Paul

**Comment by pauldangerkile** [comment]
It's correct now. Maybe you fixed it, or maybe I was wrong somehow?

**Comment by polarity** [comment]
mhh weird, i didnt changed anything. but thx for reporting :)
